const express = require('express');
const cors = require('cors');
const path = require('path');
const puppeteer = require('puppeteer');
const fs = require('fs').promises;

const app = express();
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.static(path.join(__dirname, 'public')));

// Azure Claude Config
const AZURE_CONFIG = {
  endpoint: 'https://jimmylam-code-resource.openai.azure.com/anthropic/v1/messages',
  apiKey: process.env.AZURE_ANTHROPIC_API_KEY || process.env.AZURE_KEY,
  model: 'claude-sonnet-4-6',
  version: '2023-06-01'
};

// Generate AI-powered security report
app.post('/api/generate-report', async (req, res) => {
  try {
    const { scanData, targetName, scanDate } = req.body;
    
    console.log('🔍 Generating AI security report for:', targetName);
    
    const prompt = `You are a senior penetration tester at Lumen AI Solutions. Generate a professional, enterprise-grade security assessment report.

## TARGET INFORMATION
- Target: ${targetName || 'Unknown Target'}
- Scan Date: ${scanDate || new Date().toISOString().split('T')[0]}
- Scanner: Lumen Cortex Security Platform

## SCAN DATA
${JSON.stringify(scanData, null, 2)}

## GENERATE A COMPREHENSIVE REPORT WITH:

1. **Executive Summary** (3-4 sentences for C-level executives)

2. **Risk Rating Table** with columns:
   - Finding ID
   - Title
   - Severity (Critical/High/Medium/Low/Info)
   - CVSS 3.1 Score
   - Status

3. **Detailed Findings** - For each finding include:
   - Description
   - Evidence (code blocks)
   - Impact analysis
   - CVSS vector string

4. **OWASP Top 10 2021 Mapping**

5. **Remediation Guidance** with:
   - Priority level
   - Code examples (Node.js/Python)
   - Implementation steps

6. **Compliance Implications**
   - SOC 2 Type II
   - PCI-DSS v4.0
   - HIPAA (if applicable)
   - ISO 27001

7. **Prioritized Action Plan**
   - Immediate (0-7 days)
   - Short-term (30 days)
   - Medium-term (90 days)

Format in clean, professional markdown. Use tables, code blocks, and clear headings.`;

    const response = await fetch(AZURE_CONFIG.endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': AZURE_CONFIG.apiKey,
        'anthropic-version': AZURE_CONFIG.version
      },
      body: JSON.stringify({
        model: AZURE_CONFIG.model,
        max_tokens: 8000,
        messages: [{ role: 'user', content: prompt }]
      })
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`Azure API error: ${error}`);
    }

    const data = await response.json();
    const reportContent = data.content[0].text;
    
    // Add report metadata
    const fullReport = `# 🔐 Lumen Cortex Security Assessment Report

**Target:** ${targetName || 'Unknown'}  
**Assessment Date:** ${scanDate || new Date().toISOString().split('T')[0]}  
**Generated By:** Lumen Cortex AI Security Platform  
**Classification:** CONFIDENTIAL  
**Report ID:** LUMEN-${Date.now()}

---

${reportContent}

---

## Report Metadata

| Field | Value |
|-------|-------|
| Generator | Lumen Cortex v1.0 |
| AI Engine | Azure Claude Sonnet 4.6 |
| Report Generated | ${new Date().toISOString()} |
| Classification | CONFIDENTIAL |

---

*This report was generated by Lumen Cortex AI Security Platform. Distribution is restricted to authorized personnel.*

© ${new Date().getFullYear()} Lumen AI Solutions. All rights reserved.
`;

    console.log('✅ Report generated successfully');
    
    res.json({
      success: true,
      report: fullReport,
      metadata: {
        target: targetName,
        date: scanDate,
        generatedAt: new Date().toISOString(),
        tokens: data.usage
      }
    });

  } catch (error) {
    console.error('❌ Report generation error:', error);
    res.status(500).json({ 
      success: false, 
      error: error.message 
    });
  }
});

// Export report to PDF
app.post('/api/export-pdf', async (req, res) => {
  try {
    const { reportHtml, filename } = req.body;
    
    console.log('📄 Generating PDF...');
    
    const browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    
    const page = await browser.newPage();
    
    // Professional PDF styling
    const styledHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #1a1a2e;
      padding: 40px 50px;
      background: #fff;
    }
    
    h1 {
      font-size: 24pt;
      color: #0f0f23;
      border-bottom: 3px solid #dc2626;
      padding-bottom: 15px;
      margin-bottom: 25px;
    }
    
    h2 {
      font-size: 16pt;
      color: #1e40af;
      margin-top: 30px;
      margin-bottom: 15px;
      padding-bottom: 8px;
      border-bottom: 2px solid #e5e7eb;
    }
    
    h3 {
      font-size: 13pt;
      color: #374151;
      margin-top: 20px;
      margin-bottom: 10px;
    }
    
    h4 {
      font-size: 11pt;
      color: #6b7280;
      margin-top: 15px;
      margin-bottom: 8px;
    }
    
    p {
      margin-bottom: 12px;
      text-align: justify;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
      font-size: 10pt;
    }
    
    th {
      background: #1e40af;
      color: white;
      padding: 12px 10px;
      text-align: left;
      font-weight: 600;
    }
    
    td {
      padding: 10px;
      border-bottom: 1px solid #e5e7eb;
    }
    
    tr:nth-child(even) {
      background: #f9fafb;
    }
    
    code {
      background: #f3f4f6;
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'Monaco', 'Consolas', monospace;
      font-size: 9pt;
    }
    
    pre {
      background: #1e1e2e;
      color: #cdd6f4;
      padding: 15px;
      border-radius: 8px;
      overflow-x: auto;
      margin: 15px 0;
      font-size: 9pt;
      line-height: 1.5;
    }
    
    pre code {
      background: none;
      padding: 0;
      color: inherit;
    }
    
    blockquote {
      border-left: 4px solid #fbbf24;
      background: #fef3c7;
      padding: 15px 20px;
      margin: 15px 0;
      font-style: italic;
    }
    
    ul, ol {
      margin: 10px 0 10px 25px;
    }
    
    li {
      margin-bottom: 5px;
    }
    
    .severity-critical { color: #dc2626; font-weight: 700; }
    .severity-high { color: #ea580c; font-weight: 600; }
    .severity-medium { color: #ca8a04; font-weight: 600; }
    .severity-low { color: #2563eb; }
    .severity-info { color: #6b7280; }
    
    .header-logo {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 1px solid #e5e7eb;
    }
    
    .logo-text {
      font-size: 28pt;
      font-weight: 700;
      color: #dc2626;
    }
    
    .confidential-badge {
      background: #dc2626;
      color: white;
      padding: 8px 16px;
      font-size: 9pt;
      font-weight: 600;
      border-radius: 4px;
      text-transform: uppercase;
    }
    
    .page-break {
      page-break-before: always;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      font-size: 9pt;
      color: #6b7280;
      text-align: center;
    }
    
    @media print {
      body { padding: 20px 30px; }
      h2 { page-break-after: avoid; }
      pre, table { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header-logo">
    <span class="logo-text">🔐 LUMEN CORTEX</span>
    <span class="confidential-badge">CONFIDENTIAL</span>
  </div>
  ${reportHtml}
  <div class="footer">
    <p>Generated by Lumen Cortex AI Security Platform | © ${new Date().getFullYear()} Lumen AI Solutions</p>
    <p>This document contains confidential security findings. Handle according to your organization's data classification policy.</p>
  </div>
</body>
</html>`;

    await page.setContent(styledHtml, { waitUntil: 'networkidle0' });
    
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '15mm',
        bottom: '20mm',
        left: '15mm'
      },
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: `
        <div style="font-size: 9px; width: 100%; text-align: center; color: #666;">
          <span>Lumen Cortex Security Report</span> | 
          Page <span class="pageNumber"></span> of <span class="totalPages"></span>
        </div>
      `
    });
    
    await browser.close();
    
    console.log('✅ PDF generated successfully');
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename || 'security-report'}.pdf"`);
    res.send(pdfBuffer);

  } catch (error) {
    console.error('❌ PDF generation error:', error);
    res.status(500).json({ 
      success: false, 
      error: error.message 
    });
  }
});

// Health check
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', service: 'Lumen Cortex Report Generator' });
});

// Serve the main UI
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

const PORT = process.env.PORT || 3334;
app.listen(PORT, () => {
  console.log(`
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║   🔐 LUMEN CORTEX - Report Generator                      ║
║                                                           ║
║   Server running on: http://localhost:${PORT}               ║
║   AI Engine: Azure Claude Sonnet 4.6                      ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝
  `);
});
